name: Next.js CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload .next folder
        uses: actions/upload-artifact@v2
        with:
          name: next-build
          path: .next

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download .next folder
        uses: actions/download-artifact@v2
        with:
          name: next-build
          path: .next

      - name: Deploy to Production via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.CODEJD_BACK_FTP_SERVER }}
          username: ${{ secrets.CODEJD_BACK_FTP_USERNAME }}
          password: ${{ secrets.CODEJD_BACK_FTP_PASSWORD }}
          local-dir: .next/
          server-dir: public_html/
          zip-before-upload: true
          exclude: |
            **/node_modules/**
            .git*
            .env
            .ftpignore
